const {
  REACT_APP_CRYPTO_ICON_URL,
  REACT_APP_NODE_URL,
  REACT_APP_PASSWORD_SECRET_KEY,
  REACT_APP_PASSPHRASE_WALLET_DEFAULT,
  REACT_APP_API_BASE_URL,
  REACT_APP_INCOGNITO_TOKEN_ICON_URL,
  REACT_APP_EXPLORER_CONSTANT_CHAIN_URL,
  REACT_APP_MASTER_NODE_ADDRESS,
} = process.env;

const PASSWORD_SECRET_KEY = REACT_APP_PASSWORD_SECRET_KEY || '';
const PASSPHRASE_WALLET_DEFAULT = REACT_APP_PASSPHRASE_WALLET_DEFAULT || '';
const CRYPTO_ICON_URL = REACT_APP_CRYPTO_ICON_URL || '';
const NODE_URL = REACT_APP_NODE_URL || '';
const API_BASE_URL = REACT_APP_API_BASE_URL || '';
const INCOGNITO_TOKEN_ICON_URL = REACT_APP_INCOGNITO_TOKEN_ICON_URL || '';
const EXPLORER_CONSTANT_CHAIN_URL = REACT_APP_EXPLORER_CONSTANT_CHAIN_URL || '';
const MASTER_NODE_ADDRESS = REACT_APP_MASTER_NODE_ADDRESS || '';

export default {
  CRYPTO_ICON_URL,
  INCOGNITO_TOKEN_ICON_URL,
  API_BASE_URL,
  PASSWORD_SECRET_KEY,
  EXPLORER_CONSTANT_CHAIN_URL,
  PASSPHRASE_WALLET_DEFAULT,
  MASTER_NODE_ADDRESS,
  NODE_URL,
};
