const KEYS = {
  PASSPHRASE_KEY: 'password',
  DEFAULT_ACCOUNT_NAME: 'DEFAULT_ACCOUNT_NAME',
  DEVICE_TOKEN: 'DEVICE_TOKEN',
  DISPLAYED_WIZARD: 'DISPLAYED_WIZARD',
  GAME_PLAYER_ID: 'GAME_PLAYER_ID',
  USER: 'USER_OBJECT_KEY',
  LIST_DEVICE: 'PRODUCT_LIST_KEY',
  LIST_TOKEN: 'LIST_TOKEN',
  USER_UNFOLLOWING_TOKEN_ID_LIST: 'USER_UNFOLLOWING_TOKEN_ID_LIST',
  DEX: 'DEX',
  DEX_HISTORY: 'DEX_HISTORY',
  SEEN_DEPOSIT_GUIDE: 'SEEN_DEPOSIT_GUIDE',
  WITHDRAW_REQUESTS: 'WITHDRAW_REQUESTS',
  PIN: 'PIN',
  IS_CHECK_FOLLOWED_TOKEN: 'IS_CHECK_FOLLOWED_TOKEN',
  IS_BACKEDUP_ACCOUNT: 'IS_BACKEDUP_ACCOUNT',
};

export default {
  ...KEYS,
};
