// Action types
export const GET_CHAIN_TOKENS = 'GET_CHAIN_TOKENS';
export const GET_CHAIN_TOKENS_SUCCESS = 'GET_CHAIN_TOKENS_SUCCESS';
export const GET_CHAIN_TOKENS_FAILED = 'GET_CHAIN_TOKENS_FAILED';

export const GET_BRIDGE_TOKENS = 'GET_BRIDGE_TOKENS';
export const GET_BRIDGE_TOKENS_SUCCESS = 'GET_BRIDGE_TOKENS_SUCCESS';
export const GET_BRIDGE_TOKENS_FAILED = 'GET_BRIDGE_TOKENS_FAILED';

export const LOAD_WALLET = 'LOAD_WALLET';
export const LOAD_WALLET_SUCCESS = 'LOAD_WALLET_SUCCESS';
export const LOAD_WALLET_FAILED = 'LOAD_WALLET_FAILED';

export const CREATE_WALLET = 'CREATE_WALLET';
export const CREATE_WALLET_SUCCESS = 'CREATE_WALLET_SUCCESS';
export const CREATE_WALLET_FAILED = 'CREATE_WALLET_FAILED';
